### ISSUE TITLE
Can't calculate complexity metrics "affinity", "distinct_traces" and "structure"

### ISSUE THREAD

**Issue by Frederik-Roeckle** [Frederik-Roeckle/Rep_ImpactProcessComplexity#1]
The given script of the authors for calculating the complexity Metrics ("Complexity.py") ran into errors when calculating the complexity measures:

- affinity
- distinct_traces
- structure

With all these measures the script raise an InvalidVersionException:

InvalidVersion(f"Invalid version: '{version}'") packaging.version.InvalidVersion: Invalid version: 'please use pm4py.algo.filtering.log.ltl.ltl_checker.eventually_follows'

**Comment by labonipia** [comment]
I could remove the issue - I think it was caused by an older version of pm4py. I installed pm4py 2.7.11.4 after uninstalling older version.

**Comment by Frederik-Roeckle** [comment]
Thanks for the hint I'm going to install that version and try it out again

**Comment by Frederik-Roeckle** [comment]
Thanks @labonipia When forcing the pm4py version to 2.7.11.4 it workded without a problem.

pip install --force-reinstall -v "pm4py==2.7.11.4"
